name: Renovate
on:
  schedule:
    - cron: '0 3 * * *' # Runs daily at 3 AM
  workflow_dispatch:     # Adds the manual "Run workflow" button

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4 # Brings your config.js into the runner
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@d65ef9e20512193cc070238b49c3873a361cd50c # v46.1.1 # The official Renovate "engine"
        with:
          configurationFile: config.js
          token: ${{ secrets.RENOVATE_TOKEN }} # Your PAT stored in GitHub Secrets
